//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KikoGuide.Resources.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("KikoGuide.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Commands_GuideViewer_Help {
            get {
                return ResourceManager.GetString("Commands_GuideViewer_Help", resourceCulture);
            }
        }
        
        internal static string Commands_GuideList_Help {
            get {
                return ResourceManager.GetString("Commands_GuideList_Help", resourceCulture);
            }
        }
        
        internal static string Windows_PluginSettings_Title {
            get {
                return ResourceManager.GetString("Windows_PluginSettings_Title", resourceCulture);
            }
        }
        
        internal static string Windows_GuideList_Title {
            get {
                return ResourceManager.GetString("Windows_GuideList_Title", resourceCulture);
            }
        }
        
        internal static string Windows_GuideViewer_Title {
            get {
                return ResourceManager.GetString("Windows_GuideViewer_Title", resourceCulture);
            }
        }
        
        internal static string Windows_Integrations_Title {
            get {
                return ResourceManager.GetString("Windows_Integrations_Title", resourceCulture);
            }
        }
        
        internal static string Windows_GuideSettings_Title {
            get {
                return ResourceManager.GetString("Windows_GuideSettings_Title", resourceCulture);
            }
        }
        
        internal static string Guide_NoConfig {
            get {
                return ResourceManager.GetString("Guide_NoConfig", resourceCulture);
            }
        }
        
        internal static string Commands_GuideViewer_NoGuide {
            get {
                return ResourceManager.GetString("Commands_GuideViewer_NoGuide", resourceCulture);
            }
        }
        
        internal static string Guide_NotMetRequirements {
            get {
                return ResourceManager.GetString("Guide_NotMetRequirements", resourceCulture);
            }
        }
        
        internal static string Errors_DrawFailed {
            get {
                return ResourceManager.GetString("Errors_DrawFailed", resourceCulture);
            }
        }
        
        internal static string Guide_InstanceContent_AvailableForDuty {
            get {
                return ResourceManager.GetString("Guide_InstanceContent_AvailableForDuty", resourceCulture);
            }
        }
        
        internal static string Integrations_NoConfig {
            get {
                return ResourceManager.GetString("Integrations_NoConfig", resourceCulture);
            }
        }
        
        internal static string Integrations_ForceDisabled {
            get {
                return ResourceManager.GetString("Integrations_ForceDisabled", resourceCulture);
            }
        }
        
        internal static string Integrations_Enabled {
            get {
                return ResourceManager.GetString("Integrations_Enabled", resourceCulture);
            }
        }
        
        internal static string UserInterface_Integrations_Title {
            get {
                return ResourceManager.GetString("UserInterface_Integrations_Title", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideSettings_Title {
            get {
                return ResourceManager.GetString("UserInterface_GuideSettings_Title", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideList_NoneFound {
            get {
                return ResourceManager.GetString("UserInterface_GuideList_NoneFound", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideList_NoneUnlocked_Heading {
            get {
                return ResourceManager.GetString("UserInterface_GuideList_NoneUnlocked_Heading", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideList_NoneUnlocked_Body {
            get {
                return ResourceManager.GetString("UserInterface_GuideList_NoneUnlocked_Body", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideList_NoLogin_Title {
            get {
                return ResourceManager.GetString("UserInterface_GuideList_NoLogin_Title", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideList_NoLogin_Body {
            get {
                return ResourceManager.GetString("UserInterface_GuideList_NoLogin_Body", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideList_Search_Heading {
            get {
                return ResourceManager.GetString("UserInterface_GuideList_Search_Heading", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideList_SearchHint {
            get {
                return ResourceManager.GetString("UserInterface_GuideList_SearchHint", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideList_DifficultyFilter_Heading {
            get {
                return ResourceManager.GetString("UserInterface_GuideList_DifficultyFilter_Heading", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideList_DifficultyFilter_Any {
            get {
                return ResourceManager.GetString("UserInterface_GuideList_DifficultyFilter_Any", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideList_Contributing_Heading {
            get {
                return ResourceManager.GetString("UserInterface_GuideList_Contributing_Heading", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideList_Contributing_Guides {
            get {
                return ResourceManager.GetString("UserInterface_GuideList_Contributing_Guides", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideList_Contributing_Translate {
            get {
                return ResourceManager.GetString("UserInterface_GuideList_Contributing_Translate", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideList_Contributing_Donate {
            get {
                return ResourceManager.GetString("UserInterface_GuideList_Contributing_Donate", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideList_Configuration_Heading {
            get {
                return ResourceManager.GetString("UserInterface_GuideList_Configuration_Heading", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideList_Configuration_Plugin {
            get {
                return ResourceManager.GetString("UserInterface_GuideList_Configuration_Plugin", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideList_Configuration_Integrations {
            get {
                return ResourceManager.GetString("UserInterface_GuideList_Configuration_Integrations", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideList_Configuration_Guide {
            get {
                return ResourceManager.GetString("UserInterface_GuideList_Configuration_Guide", resourceCulture);
            }
        }
        
        internal static string Guide_InstanceContent_Mechanics_Name {
            get {
                return ResourceManager.GetString("Guide_InstanceContent_Mechanics_Name", resourceCulture);
            }
        }
        
        internal static string Guide_InstanceContent_Mechanics_Description {
            get {
                return ResourceManager.GetString("Guide_InstanceContent_Mechanics_Description", resourceCulture);
            }
        }
        
        internal static string Guide_InstanceContent_Mechanics_Heading {
            get {
                return ResourceManager.GetString("Guide_InstanceContent_Mechanics_Heading", resourceCulture);
            }
        }
        
        internal static string Guide_InstanceContent_Content_Heading {
            get {
                return ResourceManager.GetString("Guide_InstanceContent_Content_Heading", resourceCulture);
            }
        }
        
        internal static string Guide_InstanceContent_Tips_Heading {
            get {
                return ResourceManager.GetString("Guide_InstanceContent_Tips_Heading", resourceCulture);
            }
        }
        
        internal static string Guide_InstanceContent_Links_Heading {
            get {
                return ResourceManager.GetString("Guide_InstanceContent_Links_Heading", resourceCulture);
            }
        }
        
        internal static string Note_Save {
            get {
                return ResourceManager.GetString("Note_Save", resourceCulture);
            }
        }
        
        internal static string Note_Edit {
            get {
                return ResourceManager.GetString("Note_Edit", resourceCulture);
            }
        }
        
        internal static string Note_Name {
            get {
                return ResourceManager.GetString("Note_Name", resourceCulture);
            }
        }
        
        internal static string Guide_InstanceContent_TypeName {
            get {
                return ResourceManager.GetString("Guide_InstanceContent_TypeName", resourceCulture);
            }
        }
        
        internal static string Guide_InstanceContent_UnnamedInstance {
            get {
                return ResourceManager.GetString("Guide_InstanceContent_UnnamedInstance", resourceCulture);
            }
        }
        
        internal static string UserInterface_Integrations_About_Body {
            get {
                return ResourceManager.GetString("UserInterface_Integrations_About_Body", resourceCulture);
            }
        }
        
        internal static string UserInterface_Integrations_About_Heading {
            get {
                return ResourceManager.GetString("UserInterface_Integrations_About_Heading", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideSettings_About_Body {
            get {
                return ResourceManager.GetString("UserInterface_GuideSettings_About_Body", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideSettings_About_Title {
            get {
                return ResourceManager.GetString("UserInterface_GuideSettings_About_Title", resourceCulture);
            }
        }
        
        internal static string UserInterface_Integrations_Configure_Heading {
            get {
                return ResourceManager.GetString("UserInterface_Integrations_Configure_Heading", resourceCulture);
            }
        }
        
        internal static string Integrations_Wotsit_Description {
            get {
                return ResourceManager.GetString("Integrations_Wotsit_Description", resourceCulture);
            }
        }
        
        internal static string UserInterface_PluginSettings_NoConfig {
            get {
                return ResourceManager.GetString("UserInterface_PluginSettings_NoConfig", resourceCulture);
            }
        }
        
        internal static string UserInterface_PluginSettings_General_Heading {
            get {
                return ResourceManager.GetString("UserInterface_PluginSettings_General_Heading", resourceCulture);
            }
        }
        
        internal static string Guide_Fate_Config_AutoOpen {
            get {
                return ResourceManager.GetString("Guide_Fate_Config_AutoOpen", resourceCulture);
            }
        }
        
        internal static string Guide_InstanceContent_Config_AutoOpen {
            get {
                return ResourceManager.GetString("Guide_InstanceContent_Config_AutoOpen", resourceCulture);
            }
        }
        
        internal static string Guide_Fate_TypeName {
            get {
                return ResourceManager.GetString("Guide_Fate_TypeName", resourceCulture);
            }
        }
        
        internal static string Note_Create {
            get {
                return ResourceManager.GetString("Note_Create", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideViewer_Tooltip_LockViewer {
            get {
                return ResourceManager.GetString("UserInterface_GuideViewer_Tooltip_LockViewer", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideViewer_Tooltip_UnlockViewer {
            get {
                return ResourceManager.GetString("UserInterface_GuideViewer_Tooltip_UnlockViewer", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideViewer_Tooltip_ShowNote {
            get {
                return ResourceManager.GetString("UserInterface_GuideViewer_Tooltip_ShowNote", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideViewer_Tooltip_ShowGuide {
            get {
                return ResourceManager.GetString("UserInterface_GuideViewer_Tooltip_ShowGuide", resourceCulture);
            }
        }
        
        internal static string Note_Delete {
            get {
                return ResourceManager.GetString("Note_Delete", resourceCulture);
            }
        }
        
        internal static string UserInterface_Global_TooltipHint {
            get {
                return ResourceManager.GetString("UserInterface_Global_TooltipHint", resourceCulture);
            }
        }
        
        internal static string UserInterface_GuideViewer_Tooltip_EnableDeleteNote {
            get {
                return ResourceManager.GetString("UserInterface_GuideViewer_Tooltip_EnableDeleteNote", resourceCulture);
            }
        }
        
        internal static string UserInterface_Toast_NoteSaved {
            get {
                return ResourceManager.GetString("UserInterface_Toast_NoteSaved", resourceCulture);
            }
        }
        
        internal static string UserInterface_Toast_NoteDeleted {
            get {
                return ResourceManager.GetString("UserInterface_Toast_NoteDeleted", resourceCulture);
            }
        }
    }
}
